server:
  port: 8080

spring:
  application:
    name: cheappool
  
  datasource:
    url: jdbc:h2:mem:cheappool;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
  
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: false
  
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  
  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    com.cheappool: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 应用自定义配置
app:
  name: CheapGPT 企业账号池
  version: 1.0.0
  chatgpt:
    api:
      base-url: https://api.openai.com
      timeout: 30s
    pool:
      round-robin-enabled: true
      health-check-interval: 5m
